apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap

data:
  index.html: |
      <h1>Welcome to my web page!</h1>
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    framework: flask
spec:
  containers:
  - name: configmap-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: my-volume
        mountPath: /usr/share/nginx/html
   
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    framework: flask
  ports:
    - port: 80 # container port
      nodePort: 30003 # host port
  type: NodePort