apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    framework: flask

spec:
  containers:
  - name: flask-container
    image: manifoldailearning/mlops_flask:v1
    ports:
    - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    framework: flask
  ports:
    - port: 8002 # container port
      nodePort: 30002 # host port
  type: NodePort