apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: username
  password: pwd12345678

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    framework: flask

spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password